title: Kit de Campagne Numérique pour Insoumis·e
url: "kitcampagne.fi"


# Build settings
permalink: /:title/
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
