title: Kit de Campagne Numérique pour Insoumis·e

# Build settings
permalink: /:title/
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
collections:
  cat_franceinsoumise:
    output: true
    permalink: franceinsoumise/:name/
    title: La France Insoumise
  cat_legislatives2017:
    output: true
    permalink: legislatives2017/:name/
    title: Législatives 2017
  cat_reseauxsociaux:
    output: true
    permalink: reseauxsociaux/:name/
    title: Réseaux sociaux
  cat_discord:
    output: true
    permalink: discord/:name/
    title: Discord
collection_order:
  - cat_franceinsoumise
  - cat_legislatives2017
  - cat_reseauxsociaux
  - cat_discord
sass:
  sass_dir: _sass
  style: compressed
autoprefixer:
  browsers:
  - last 2 versions
